#!/usr/bin/env bash
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

sudo cp -f $dir/tormix /usr/bin/ 

if [ ! -d "$HOME/.config/tormix/themes" ]; then
	mkdir -p $HOME/.config/tormix/themes
fi
cp -f $dir/themes/* $HOME/.config/tormix/themes
sudo chown -R $USER:$USER $HOME/.config/tormix
sudo rm /usr/share/man/man1/tormix.1.gz &>/dev/null
sudo cp -f $dir/tormix.1 /usr/share/man/man1/
sudo gzip /usr/share/man/man1/tormix.1
